### PR TITLE
Feature/mapay schema

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Created Schema for MAPay Register Licensed Professional

### CODE REVIEW

**Comment by nick-verida** [comment]
@cmcWebCode40 I assume these changes were made when we moved to the other repo?

**Comment by nick-verida** [comment]
@cmcWebCode40 I assume this was migrated to the new repo? Can we just delete this PR?

**Comment by cmcWebCode40** [comment]
Yes, @nick-verida we can delete it, 

 it was migrated to this repo https://github.com/verida/demo-credential-issuer

**Comment by nick-verida** [comment]
Closing. Outdated

**Pull request closed without merging**
